networks:
  talkie-net:
    driver: bridge
volumes:
  postgres-data:
  mongo-data:
  redis-data:
  minio-data:
  prometheus-data:
  grafana-data:
services:
  postgres:
    image: postgres:17
    container_name: postgres_c
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST_AUTH_METHOD=md5
    networks:
      - talkie-net
    volumes:
      - ./infrastructure/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -h localhost -p 5432" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
  mongoDB:
    image: mongo:7.0
    container_name: mongo_c
    networks:
      - talkie-net
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping').ok", "--quiet" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
  redis:
    image: redis:7.2
    container_name: redis_c
    networks:
      - talkie-net
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
  minio:
    image: minio/minio:RELEASE.2024-01-16T16-07-38Z
    container_name: minio_c
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - talkie-net
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
  prometheus:
    image: prom/prometheus:v2.37.0
    container_name: prometheus_c
    volumes:
      - ./infrastructure/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - talkie-net

  grafana:
    image: grafana/grafana:9.5.0
    container_name: grafana_c
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3100:3000"
    networks:
      - talkie-net
    depends_on:
      - prometheus
